PACKAGE_NAME="umip-limit-fix-linuwux"
PACKAGE_VERSION="1.0.0"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"

BUILT_MODULE_NAME[0]="umip_limit_fix_linuwux"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/kernel/arch/x86/kernel"

AUTOINSTALL="yes"
